

import random
elemento1="Friends"
elemento2="Breaking Bad"
elemento3="Arquivo X"
elemento4="Game of Thrones"
elemento5="Seinfeld"
elemento6="Família Soprano"
elemento7="Mad Men"
elemento8="Os Simpsons"
elemento9="Grey’s Anatomy"
elemento10="Modern Family"
elemento11="Arrested Development"
elemento12="Twin Peaks"
elemento13="House of Cards"
elemento14="Atypical"
elemento15="Orange Is the New Black"
elemento16="Sherlock-UK"
elemento17="Dexter"
elemento18="Orphan Black"
elemento19="Freaks and Geeks"
elemento20="True Detective"
elemento21="The Shield"
elemento22="Dr. House"
elemento23="Law e Order"
elemento24="Dawson's Creek"
elemento25="The OC"
elemento26="MacGyver"
elemento27="Shameless-US"
elemento28="How to get away with Murder"
elemento29="Transparent"
elemento30="The Fosters"
elemento31="Dirk Gently's Holistic Detective Agency"
elemento32="Sense8"
elemento33="Misfits"
elemento34="Travelers"
elemento35="Doctor Who"
elemento36="Control Z"
elemento37="American Horror Story"
elemento38="The Order"
elemento39="Bates Motel"
elemento40="Hemlock Grove"
elemento41="Castle Rock"
elemento42="Killing Eve"
elemento43="The Rain"
elemento44="Bom dia, Verônica"
elemento45="Requiem"
elemento46="The Sinner"
elemento47="Awkward"
elemento48="Sex Education"
elemento49="Dickinson"
elemento50="The Bold Type"
elemento51="Young Royals"
elemento52="Brooklyn Nine-Nine"
elemento53="Sexify"
elemento54="Gossip Girl"
elemento55="Behind Her Eyes"
elemento56="The Haunting of Bly Manor"
elemento57="Ozark"
elemento58="Unbelievable"
elemento59="Mindhunter"
elemento60="Skins"
elemento61="Fleabag"
elemento62="A Young Doctor’s Notebook"
elemento63="Sick Note"
elemento64="This is Us"
elemento65="Sons of Anarchy"
elemento66="Penny Dreadful"
elemento67="Forever"
elemento68="Lucifer"
elemento69="Good Girls"
elemento70="Bones"
elemento71="Faking It"
elemento72="White Collar"
elemento73="Jessica Jones"
elemento74="Hunters"
elemento75="The boys"
elemento76="The Wilds"
elemento77="Carnival Row"
elemento78="Sweet Tooth"
elemento79="Good Omens"
elemento80="The Good Doctor"

lista=[elemento1,elemento2,elemento3,elemento4,elemento5,elemento6,elemento7,elemento8, elemento9,elemento10, elemento11, elemento12, elemento13, elemento14, elemento15, elemento16, elemento17, elemento18,elemento19, elemento20, elemento21, elemento22, elemento23,elemento24,elemento25,elemento26,elemento27, elemento28, elemento29, elemento30,elemento31, elemento32,elemento33,elemento34,elemento35,elemento36,elemento37,elemento38,elemento39,elemento40,elemento41,elemento42,elemento43,elemento44, elemento45,elemento46,elemento47,elemento48,elemento49,elemento50,elemento51,elemento52,elemento53,elemento54,elemento55,elemento56,elemento57,elemento58,elemento59,elemento60,elemento61,elemento62,elemento63,elemento64,elemento65,elemento66,elemento67,elemento68,elemento69,elemento70,elemento71,elemento72,elemento73,elemento74,elemento75,elemento76,elemento77,elemento78,elemento79,elemento80]

print("Esse programa foi feito para você que passa mais tempo procurando que série nova deve começar, do que de fato assistindo-a!Que tal arriscar um pouco e me deixar te dizer o que assistir hoje?")

sorteio = random.choice(lista)

print('A sugestão de hoje é:', sorteio)
